Db status
KarmaKamikaze/TRACE-Q-UI pull request #17
Opened 2024-05-02 11:52 UTC by Mailaur

Added check status button to status endpoint.

2024-05-02 11:53 UTC, KarmaKamikaze commented
Kan du tilføje screenshots af UI til pull requesten? Det ville være fedt at se in-action.

2024-05-02 12:16 UTC, Kristoffermg requested changes

2024-05-02 12:16 UTC, Kristoffermg commented on templates/index.html
> +                    <ul class="dropdown-menu">
"presentation" knapperne er blevet erstattet med den gamle dropdown her

2024-05-03 07:35 UTC, Kristoffermg approved these changes
Ser godt ud

2024-05-03 07:36 UTC, Mailaur commented
![image](https://github.com/KarmaKamikaze/TRACE-Q-UI/assets/44166342/99d140db-d29f-4509-8250-2b6f5d68634a)

![image](https://github.com/KarmaKamikaze/TRACE-Q-UI/assets/44166342/39863512-251a-4f8b-b3ad-f1d725e4b3d6)

![image](https://github.com/KarmaKamikaze/TRACE-Q-UI/assets/44166342/21039157-1c0f-4526-9f2f-f61a4ec8cdda)

![image](https://github.com/KarmaKamikaze/TRACE-Q-UI/assets/44166342/690ac50f-7b2f-48e1-8047-190421f66bb9)

2024-05-03 07:45 UTC, merged